version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  server:
    build: .
    container_name:  "server"
    ports:
      - "8000:8000"
  
  server2:
    build:
      context: server2
      dockerfile: ./Dockerfile.server2
    container_name: "server2"
    ports:
      - "8001:8001"
    
    
 
volumes:
  pgdata: